my_blog/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.indexs, name='index'),
    url(r'^article/(?P<article_id>\d+)$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>\d+)$', views.edit_page, name='edit_page'),
    url(r'^edit/action/$', views.edit_action, name='edit_action')
]

my_blog/my_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^user/', include('user.urls'))
]

my_blog/user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index)
]

my_blog/blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(null=True)

    def __str__(self):
        return self.title

my_blog/user/models.py
from django.db import models

# Create your models here.

my_blog/blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from . import models


def indexs(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    article_id = request.POST.get('article_id', '0')
    if article_id == '0':
        models.Article.objects.create(title=title, content=content)
        return redirect('blog:index')

    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    return redirect('blog:article_page', article_id=article_id)

my_blog/user/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'user/index.html', {'hello': 'Hello, Blog!'})

my_blog/blog/templates/blog/article_page.html
{% extends 'blog/header.html' %}
{% block content %}
    <h1 class="text-center">{{ article.title }}</h1>
    <div class="col-md-2"></div>
    <div class="text-center col-md-8">
        <h4>{{ article.content }}</h4>
        <a class="btn btn-default text-center" href="{% url 'blog:edit_page' article.id %}">修改文章</a>
        <a class="btn btn-default" href="{% url 'blog:index' %}">返回主页</a>
    </div>
    <div class="col-md-2"></div>
{% endblock %}

my_blog/blog/templates/blog/edit_page.html
{% extends 'blog/header.html' %}
{% block content %}
    <form action="{% url 'blog:edit_action' %}" method="post" class="text-center">
        {% csrf_token %}
        <h3>新建鸡汤</h3>
        <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}">
        <div class="form-group">
            <label>文章标题
                <input class="form-control" type="text" name="title" value="{{ article.title }}"/>
            </label>
        </div>
        <div class="form-group">
            <label>文章内容
                <textarea class="form-control" name="content">{{ article.content }}</textarea>
            </label>
        </div>
        <button class="btn btn-default" type="submit">提交</button>
    </form>
{% endblock %}

my_blog/blog/templates/blog/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BLOG</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}"/>
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

my_blog/blog/templates/blog/index.html
{% extends 'blog/header.html' %}
{% block content %}
    <h1 class="text-center">主页</h1>

    <div class="text-center">
        <a class="btn btn-default" href="{% url 'blog:edit_page' 0 %}">新建鸡汤</a>
        <br/>
        {% for article in articles %}
            <h3>
                <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
            </h3>
        {% endfor %}
    </div>
{% endblock %}

my_blog/user/templates/user/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Hello, user!</h1>
</body>
</html>